# Generated by Django 4.1.3 on 2022-12-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioStored",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record", models.FileField(upload_to="documents/")),
            ],
            options={
                "db_table": "AudioStored",
            },
        ),
    ]
