# Generated by Django 4.1.3 on 2022-12-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songPredict", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiostored",
            old_name="record",
            new_name="song",
        ),
    ]
